# Micrograd
**The 20th Summer Project**

**Noted and Created by Han summer 2024**

Based on Karpathy's Micrograd library

This notebook is the same thing but using pytorch library

In [1]:
import torch

Micrograd is a scalar value engine

But in torch, everything is based on tensors (n-dimensional arrays of scalars)

In [8]:
#Example tensor
torch.Tensor([[1,2,3], [4,5,6]]) #2x3 array of scalars in a single compact representation (like tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.Tensor([[1,2,3], [4,5,6]]).shape

torch.Size([2, 3])

In [9]:
torch.Tensor([2.0])

tensor([2.])

In [13]:
torch.Tensor([2.0]).dtype #single precision floating point number

torch.float32

In [10]:
torch.Tensor([2.0]).double() #Casts it to double,
#because python by default uses double precision for its floating point numbers, so casting this would make it identical to the micrograd without torch

tensor([2.], dtype=torch.float64)

In [2]:
#initialize a tensor with a scalar value
#requires_grad is a flag that tells pytorch to keep track of the gradient of the tensor. Torch assumes that leaf nodes do not require gradients for efficiency reasons since usually inputs does not need gradients
# Inputs (leaf nodes)
x1 = torch.Tensor([2.0]).double()                ; x1.requires_grad = True 
x2 = torch.Tensor([0.0]).double()                ; x2.requires_grad = True
w1 = torch.Tensor([-3.0]).double()               ; w1.requires_grad = True
w2 = torch.Tensor([1.0]).double()                ; w2.requires_grad = True
b = torch.Tensor([6.8813735870195432]).double()  ; b.requires_grad = True
#Compute the forward pass
n = x1*w1 + x2*w2 + b
o = torch.tanh(n)

print(o.data.item()) #.item() is used to extract the value from the tensor
#Compute the backward pass
o.backward()

print('---')
print('x2', x2.grad.item())
print('w2', w2.grad.item())
print('x1', x1.grad.item())
print('w1', w1.grad.item())

0.7071066904050358
---
x2 0.5000001283844369
w2 0.0
x1 -1.5000003851533106
w1 1.0000002567688737
